name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: installdeps
        run: brew install openssl
      - name: make
        run: CFLAGS="-I/usr/local/opt/openssl/include/" LDFLAGS="-L/usr/local/opt/openssl/lib/" make

