name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    env:
      CFLAGS: "-I/usr/local/ssl/include/"
      LDFLAGS: "-L/usr/local/ssl/lib/"
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
