name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: envset
        env:
          CFLAGS: "-I/usr/local/opt/openssl/include/"
          LDFLAGS: "-L/usr/local/opt/openssl/lib/"
      - name: make
        run: CFLAGS= LDFLAGS= make

