name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    env:
      CFLAGS: "-I/usr/local/opt/openssl/include/"
      LDFLAGS: "-L/usr/local/opt/openssl/lib/"
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: openssl
      run: find /usr -type f -name md5.h
